/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PressRouteImport } from './routes/press'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BiographyRouteImport } from './routes/biography'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewsIndexRouteImport } from './routes/interviews.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as InterviewsMediaRouteImport } from './routes/interviews.media'
import { Route as InterviewsCommentaryRouteImport } from './routes/interviews.commentary'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BiographyRoute = BiographyRouteImport.update({
  id: '/biography',
  path: '/biography',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIndexRoute = InterviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InterviewsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsMediaRoute = InterviewsMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => InterviewsRoute,
} as any)
const InterviewsCommentaryRoute = InterviewsCommentaryRouteImport.update({
  id: '/commentary',
  path: '/commentary',
  getParentRoute: () => InterviewsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/biography': typeof BiographyRoute
  '/contact': typeof ContactRoute
  '/interviews': typeof InterviewsRouteWithChildren
  '/news': typeof NewsRoute
  '/press': typeof PressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/interviews/commentary': typeof InterviewsCommentaryRoute
  '/interviews/media': typeof InterviewsMediaRoute
  '/blog/': typeof BlogIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/biography': typeof BiographyRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/press': typeof PressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/interviews/commentary': typeof InterviewsCommentaryRoute
  '/interviews/media': typeof InterviewsMediaRoute
  '/blog': typeof BlogIndexRoute
  '/interviews': typeof InterviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/biography': typeof BiographyRoute
  '/contact': typeof ContactRoute
  '/interviews': typeof InterviewsRouteWithChildren
  '/news': typeof NewsRoute
  '/press': typeof PressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/interviews/commentary': typeof InterviewsCommentaryRoute
  '/interviews/media': typeof InterviewsMediaRoute
  '/blog/': typeof BlogIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archives'
    | '/auth'
    | '/biography'
    | '/contact'
    | '/interviews'
    | '/news'
    | '/press'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/interviews/commentary'
    | '/interviews/media'
    | '/blog/'
    | '/interviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/archives'
    | '/auth'
    | '/biography'
    | '/contact'
    | '/news'
    | '/press'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/interviews/commentary'
    | '/interviews/media'
    | '/blog'
    | '/interviews'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archives'
    | '/auth'
    | '/biography'
    | '/contact'
    | '/interviews'
    | '/news'
    | '/press'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/interviews/commentary'
    | '/interviews/media'
    | '/blog/'
    | '/interviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchivesRoute: typeof ArchivesRoute
  AuthRoute: typeof AuthRoute
  BiographyRoute: typeof BiographyRoute
  ContactRoute: typeof ContactRoute
  InterviewsRoute: typeof InterviewsRouteWithChildren
  NewsRoute: typeof NewsRoute
  PressRoute: typeof PressRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biography': {
      id: '/biography'
      path: '/biography'
      fullPath: '/biography'
      preLoaderRoute: typeof BiographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/': {
      id: '/interviews/'
      path: '/'
      fullPath: '/interviews/'
      preLoaderRoute: typeof InterviewsIndexRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/media': {
      id: '/interviews/media'
      path: '/media'
      fullPath: '/interviews/media'
      preLoaderRoute: typeof InterviewsMediaRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/interviews/commentary': {
      id: '/interviews/commentary'
      path: '/commentary'
      fullPath: '/interviews/commentary'
      preLoaderRoute: typeof InterviewsCommentaryRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InterviewsRouteChildren {
  InterviewsCommentaryRoute: typeof InterviewsCommentaryRoute
  InterviewsMediaRoute: typeof InterviewsMediaRoute
  InterviewsIndexRoute: typeof InterviewsIndexRoute
}

const InterviewsRouteChildren: InterviewsRouteChildren = {
  InterviewsCommentaryRoute: InterviewsCommentaryRoute,
  InterviewsMediaRoute: InterviewsMediaRoute,
  InterviewsIndexRoute: InterviewsIndexRoute,
}

const InterviewsRouteWithChildren = InterviewsRoute._addFileChildren(
  InterviewsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchivesRoute: ArchivesRoute,
  AuthRoute: AuthRoute,
  BiographyRoute: BiographyRoute,
  ContactRoute: ContactRoute,
  InterviewsRoute: InterviewsRouteWithChildren,
  NewsRoute: NewsRoute,
  PressRoute: PressRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
